// <auto-generated />
namespace IssueTracker.Migrations.WitConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Added_MainName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_MainName));
        
        string IMigrationMetadata.Id
        {
            get { return "202007162352148_Added_MainName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
